name: Cache Dependencies Test

on:
  push:
    branches:
      - main

jobs:
  cache-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: prime-cache-4fb03de   # <-- THIS id is what outputs the cache-hit
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: cache-4fb03de

      - name: Show cache result
        run: echo "Cache hit: ${{ steps.prime-cache-4fb03de.outputs.cache-hit }}"
